import { config } from "dotenv";
config();
const PORT = process.env.PORT;
const DATABASE_URL = process.env.DATABASE_URL;
const SALT = process.env.SALT;
const JWT_ACCESS_SECRET = process.env.JWT_ACCESS_TOKEN_SECRET_KEY;
const JWT_REFRESH_SECRET = process.env.JWT_REFRESH_TOKEN_SECRET_KEY;
const JWT_EMAIL_RESET_SECRET = process.env.JWT_EMAIL_RESET_SECRET_KEY;
const FRONTEND_HOST = process.env.FRONTEND_HOST || 'http://localhost:3000';
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const GOOGLE_REDIRECT_URI = process.env.GOOGLE_REDIRECT_URI || FRONTEND_HOST;
const CHAT_GPT_API_KEY = process.env.chat_Gpt_Api_key || process.env.CHAT_GPT_API_KEY;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const GEMINI_PROJECT_ID = process.env.GEMINI_PROJECT_ID;
const GEMINI_REGION = process.env.GEMINI_REGION;
const GEMINI_MODEL = process.env.GEMINI_MODEL || "gemini-3.1-flash-lite";

export {
    PORT, DATABASE_URL, SALT,
    JWT_ACCESS_SECRET, JWT_REFRESH_SECRET, JWT_EMAIL_RESET_SECRET,
    FRONTEND_HOST,
    GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REDIRECT_URI,
    CHAT_GPT_API_KEY,
    GEMINI_API_KEY, GEMINI_PROJECT_ID, GEMINI_REGION, GEMINI_MODEL,
};
