import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  LucideShoppingBag,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Users,
  UserCircle2Icon,
  UserPen,
  UserX2Icon,
  X,
  Ticket,
  CreditCardIcon,
  ListOrdered,
  Palette,
  ImageIcon,
  Microscope,
  BookMarked,
  School,
  Award,
  User,
  UsersRound,
  GraduationCap,
  MessageSquare,
  Mail,
  BadgeIndianRupee,
  IndianRupee,
  Banknote,
  MessageCircle,
  ChartNoAxesCombined,
  Mails,
  Rocket,
  Download,
  MessageCircleMore,
  LaptopMinimal,
  MessageCircleQuestion,
  ScrollText,
  ReceiptIndianRupee,
  TvMinimal
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  product: LucideShoppingBag,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  userPen: UserPen,
  user2: UserCircle2Icon,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  users: Users,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  check: Check,
  ticket: Ticket,
  creditCard: CreditCardIcon,
  listOrdered: ListOrdered,
  palette: Palette,
  image: ImageIcon,
  microscope: Microscope,
  bookmark: BookMarked,
  school: School,
  award: Award,
  user: User,
  usersround: UsersRound,
  cap: GraduationCap,
  'message-square': MessageSquare,
  mail: Mail,
  'badge-indian-rupee': BadgeIndianRupee,
  'indian-rupee': IndianRupee,
  banknote: Banknote,
  'message-circle': MessageCircle,
  'chart-no-axes-combined': ChartNoAxesCombined,
  mails: Mails,
  rocket: Rocket,
  download: Download,
  'message-circle-more': MessageCircleMore,
  'laptop-minimal': LaptopMinimal,
  'message-circle-question': MessageCircleQuestion,
  'scroll-text': ScrollText,
  'receipt-indian-rupee': ReceiptIndianRupee,
  mediaTV: TvMinimal
};
